/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.dSLSAT;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.dSLSAT.DSLSATFactory
 * @model kind="package"
 * @generated
 */
public interface DSLSATPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dSLSAT";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/DSLSAT";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dSLSAT";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DSLSATPackage eINSTANCE = org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.FormImpl <em>Form</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.FormImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getForm()
   * @generated
   */
  int FORM = 0;

  /**
   * The feature id for the '<em><b>Annot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM__ANNOT = 0;

  /**
   * The feature id for the '<em><b>Form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM__FORM = 1;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM__PATH = 2;

  /**
   * The number of structural features of the '<em>Form</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.AnnotationImpl <em>Annotation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.AnnotationImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getAnnotation()
   * @generated
   */
  int ANNOTATION = 1;

  /**
   * The feature id for the '<em><b>Solver</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOTATION__SOLVER = 0;

  /**
   * The number of structural features of the '<em>Annotation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ANNOTATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.VarImpl <em>Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.VarImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getVar()
   * @generated
   */
  int VAR = 2;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__ID = 0;

  /**
   * The number of structural features of the '<em>Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.ConstImpl <em>Const</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.ConstImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getConst()
   * @generated
   */
  int CONST = 3;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST__VAL = 0;

  /**
   * The number of structural features of the '<em>Const</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.BiImplFormImpl <em>Bi Impl Form</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.BiImplFormImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getBiImplForm()
   * @generated
   */
  int BI_IMPL_FORM = 4;

  /**
   * The feature id for the '<em><b>Annot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BI_IMPL_FORM__ANNOT = FORM__ANNOT;

  /**
   * The feature id for the '<em><b>Form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BI_IMPL_FORM__FORM = FORM__FORM;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BI_IMPL_FORM__PATH = FORM__PATH;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BI_IMPL_FORM__LEFT = FORM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BI_IMPL_FORM__RIGHT = FORM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Bi Impl Form</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BI_IMPL_FORM_FEATURE_COUNT = FORM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.ImplFormImpl <em>Impl Form</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.ImplFormImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getImplForm()
   * @generated
   */
  int IMPL_FORM = 5;

  /**
   * The feature id for the '<em><b>Annot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPL_FORM__ANNOT = FORM__ANNOT;

  /**
   * The feature id for the '<em><b>Form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPL_FORM__FORM = FORM__FORM;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPL_FORM__PATH = FORM__PATH;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPL_FORM__LEFT = FORM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPL_FORM__RIGHT = FORM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Impl Form</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPL_FORM_FEATURE_COUNT = FORM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.OrFormImpl <em>Or Form</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.OrFormImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getOrForm()
   * @generated
   */
  int OR_FORM = 6;

  /**
   * The feature id for the '<em><b>Annot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FORM__ANNOT = FORM__ANNOT;

  /**
   * The feature id for the '<em><b>Form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FORM__FORM = FORM__FORM;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FORM__PATH = FORM__PATH;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FORM__LEFT = FORM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FORM__RIGHT = FORM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or Form</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FORM_FEATURE_COUNT = FORM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.AndFormImpl <em>And Form</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.AndFormImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getAndForm()
   * @generated
   */
  int AND_FORM = 7;

  /**
   * The feature id for the '<em><b>Annot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FORM__ANNOT = FORM__ANNOT;

  /**
   * The feature id for the '<em><b>Form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FORM__FORM = FORM__FORM;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FORM__PATH = FORM__PATH;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FORM__LEFT = FORM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FORM__RIGHT = FORM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And Form</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FORM_FEATURE_COUNT = FORM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.NandFormImpl <em>Nand Form</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.NandFormImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getNandForm()
   * @generated
   */
  int NAND_FORM = 8;

  /**
   * The feature id for the '<em><b>Annot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAND_FORM__ANNOT = FORM__ANNOT;

  /**
   * The feature id for the '<em><b>Form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAND_FORM__FORM = FORM__FORM;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAND_FORM__PATH = FORM__PATH;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAND_FORM__LEFT = FORM_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAND_FORM__RIGHT = FORM_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Nand Form</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAND_FORM_FEATURE_COUNT = FORM_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.dSLSAT.impl.NotFormImpl <em>Not Form</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.dSLSAT.impl.NotFormImpl
   * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getNotForm()
   * @generated
   */
  int NOT_FORM = 9;

  /**
   * The feature id for the '<em><b>Annot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FORM__ANNOT = FORM__ANNOT;

  /**
   * The feature id for the '<em><b>Form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FORM__FORM = FORM__FORM;

  /**
   * The feature id for the '<em><b>Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FORM__PATH = FORM__PATH;

  /**
   * The number of structural features of the '<em>Not Form</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FORM_FEATURE_COUNT = FORM_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.Form <em>Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Form</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Form
   * @generated
   */
  EClass getForm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.Form#getAnnot <em>Annot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Annot</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Form#getAnnot()
   * @see #getForm()
   * @generated
   */
  EReference getForm_Annot();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.Form#getForm <em>Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Form</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Form#getForm()
   * @see #getForm()
   * @generated
   */
  EReference getForm_Form();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.dSLSAT.Form#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Path</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Form#getPath()
   * @see #getForm()
   * @generated
   */
  EAttribute getForm_Path();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.Annotation <em>Annotation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Annotation</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Annotation
   * @generated
   */
  EClass getAnnotation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.dSLSAT.Annotation#getSolver <em>Solver</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Solver</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Annotation#getSolver()
   * @see #getAnnotation()
   * @generated
   */
  EAttribute getAnnotation_Solver();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.Var <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Var
   * @generated
   */
  EClass getVar();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.dSLSAT.Var#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Var#getId()
   * @see #getVar()
   * @generated
   */
  EAttribute getVar_Id();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.Const <em>Const</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Const</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Const
   * @generated
   */
  EClass getConst();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.dSLSAT.Const#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.Const#getVal()
   * @see #getConst()
   * @generated
   */
  EAttribute getConst_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.BiImplForm <em>Bi Impl Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bi Impl Form</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.BiImplForm
   * @generated
   */
  EClass getBiImplForm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.BiImplForm#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.BiImplForm#getLeft()
   * @see #getBiImplForm()
   * @generated
   */
  EReference getBiImplForm_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.BiImplForm#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.BiImplForm#getRight()
   * @see #getBiImplForm()
   * @generated
   */
  EReference getBiImplForm_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.ImplForm <em>Impl Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Impl Form</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.ImplForm
   * @generated
   */
  EClass getImplForm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.ImplForm#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.ImplForm#getLeft()
   * @see #getImplForm()
   * @generated
   */
  EReference getImplForm_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.ImplForm#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.ImplForm#getRight()
   * @see #getImplForm()
   * @generated
   */
  EReference getImplForm_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.OrForm <em>Or Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Form</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.OrForm
   * @generated
   */
  EClass getOrForm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.OrForm#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.OrForm#getLeft()
   * @see #getOrForm()
   * @generated
   */
  EReference getOrForm_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.OrForm#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.OrForm#getRight()
   * @see #getOrForm()
   * @generated
   */
  EReference getOrForm_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.AndForm <em>And Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Form</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.AndForm
   * @generated
   */
  EClass getAndForm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.AndForm#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.AndForm#getLeft()
   * @see #getAndForm()
   * @generated
   */
  EReference getAndForm_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.AndForm#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.AndForm#getRight()
   * @see #getAndForm()
   * @generated
   */
  EReference getAndForm_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.NandForm <em>Nand Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nand Form</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.NandForm
   * @generated
   */
  EClass getNandForm();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.NandForm#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.NandForm#getLeft()
   * @see #getNandForm()
   * @generated
   */
  EReference getNandForm_Left();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.dSLSAT.NandForm#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.NandForm#getRight()
   * @see #getNandForm()
   * @generated
   */
  EReference getNandForm_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.dSLSAT.NotForm <em>Not Form</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Form</em>'.
   * @see org.xtext.example.mydsl.dSLSAT.NotForm
   * @generated
   */
  EClass getNotForm();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DSLSATFactory getDSLSATFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.FormImpl <em>Form</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.FormImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getForm()
     * @generated
     */
    EClass FORM = eINSTANCE.getForm();

    /**
     * The meta object literal for the '<em><b>Annot</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORM__ANNOT = eINSTANCE.getForm_Annot();

    /**
     * The meta object literal for the '<em><b>Form</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FORM__FORM = eINSTANCE.getForm_Form();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORM__PATH = eINSTANCE.getForm_Path();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.AnnotationImpl <em>Annotation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.AnnotationImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getAnnotation()
     * @generated
     */
    EClass ANNOTATION = eINSTANCE.getAnnotation();

    /**
     * The meta object literal for the '<em><b>Solver</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ANNOTATION__SOLVER = eINSTANCE.getAnnotation_Solver();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.VarImpl <em>Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.VarImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getVar()
     * @generated
     */
    EClass VAR = eINSTANCE.getVar();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR__ID = eINSTANCE.getVar_Id();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.ConstImpl <em>Const</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.ConstImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getConst()
     * @generated
     */
    EClass CONST = eINSTANCE.getConst();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONST__VAL = eINSTANCE.getConst_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.BiImplFormImpl <em>Bi Impl Form</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.BiImplFormImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getBiImplForm()
     * @generated
     */
    EClass BI_IMPL_FORM = eINSTANCE.getBiImplForm();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BI_IMPL_FORM__LEFT = eINSTANCE.getBiImplForm_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BI_IMPL_FORM__RIGHT = eINSTANCE.getBiImplForm_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.ImplFormImpl <em>Impl Form</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.ImplFormImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getImplForm()
     * @generated
     */
    EClass IMPL_FORM = eINSTANCE.getImplForm();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPL_FORM__LEFT = eINSTANCE.getImplForm_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPL_FORM__RIGHT = eINSTANCE.getImplForm_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.OrFormImpl <em>Or Form</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.OrFormImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getOrForm()
     * @generated
     */
    EClass OR_FORM = eINSTANCE.getOrForm();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_FORM__LEFT = eINSTANCE.getOrForm_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_FORM__RIGHT = eINSTANCE.getOrForm_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.AndFormImpl <em>And Form</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.AndFormImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getAndForm()
     * @generated
     */
    EClass AND_FORM = eINSTANCE.getAndForm();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_FORM__LEFT = eINSTANCE.getAndForm_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_FORM__RIGHT = eINSTANCE.getAndForm_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.NandFormImpl <em>Nand Form</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.NandFormImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getNandForm()
     * @generated
     */
    EClass NAND_FORM = eINSTANCE.getNandForm();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAND_FORM__LEFT = eINSTANCE.getNandForm_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAND_FORM__RIGHT = eINSTANCE.getNandForm_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.dSLSAT.impl.NotFormImpl <em>Not Form</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.dSLSAT.impl.NotFormImpl
     * @see org.xtext.example.mydsl.dSLSAT.impl.DSLSATPackageImpl#getNotForm()
     * @generated
     */
    EClass NOT_FORM = eINSTANCE.getNotForm();

  }

} //DSLSATPackage
