/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.DSLSAT.ui.internal.DSLSATActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DSLSATExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DSLSATActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DSLSATActivator activator = DSLSATActivator.getInstance();
		return activator != null ? activator.getInjector(DSLSATActivator.ORG_XTEXT_EXAMPLE_MYDSL_DSLSAT) : null;
	}

}
