/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.DSLSATStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DSLSATStandaloneSetup extends DSLSATStandaloneSetupGenerated {
  public static void doSetup() {
    new DSLSATStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
