/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.dSLSAT.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.dSLSAT.DSLSATPackage;
import org.xtext.example.mydsl.dSLSAT.NotForm;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Not Form</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NotFormImpl extends FormImpl implements NotForm
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NotFormImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DSLSATPackage.Literals.NOT_FORM;
  }

} //NotFormImpl
