/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.dSLSAT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Form</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.dSLSAT.Form#getXheck <em>Xheck</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.dSLSAT.Form#getForm <em>Form</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.dSLSAT.DSLSATPackage#getForm()
 * @model
 * @generated
 */
public interface Form extends EObject
{
  /**
   * Returns the value of the '<em><b>Xheck</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Xheck</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xheck</em>' attribute.
   * @see #setXheck(String)
   * @see org.xtext.example.mydsl.dSLSAT.DSLSATPackage#getForm_Xheck()
   * @model
   * @generated
   */
  String getXheck();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.dSLSAT.Form#getXheck <em>Xheck</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xheck</em>' attribute.
   * @see #getXheck()
   * @generated
   */
  void setXheck(String value);

  /**
   * Returns the value of the '<em><b>Form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Form</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Form</em>' containment reference.
   * @see #setForm(EObject)
   * @see org.xtext.example.mydsl.dSLSAT.DSLSATPackage#getForm_Form()
   * @model containment="true"
   * @generated
   */
  EObject getForm();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.dSLSAT.Form#getForm <em>Form</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Form</em>' containment reference.
   * @see #getForm()
   * @generated
   */
  void setForm(EObject value);

} // Form
