/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.dSLSAT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Impl Form</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.dSLSAT.ImplForm#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.dSLSAT.ImplForm#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.dSLSAT.DSLSATPackage#getImplForm()
 * @model
 * @generated
 */
public interface ImplForm extends Form
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Form)
   * @see org.xtext.example.mydsl.dSLSAT.DSLSATPackage#getImplForm_Left()
   * @model containment="true"
   * @generated
   */
  Form getLeft();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.dSLSAT.ImplForm#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Form value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Form)
   * @see org.xtext.example.mydsl.dSLSAT.DSLSATPackage#getImplForm_Right()
   * @model containment="true"
   * @generated
   */
  Form getRight();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.dSLSAT.ImplForm#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Form value);

} // ImplForm
