/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.dSLSAT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Not Form</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.dSLSAT.DSLSATPackage#getNotForm()
 * @model
 * @generated
 */
public interface NotForm extends Form
{
} // NotForm
