/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalDSLSATParser;
import org.xtext.example.mydsl.services.DSLSATGrammarAccess;

public class DSLSATParser extends AbstractAntlrParser {

	@Inject
	private DSLSATGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDSLSATParser createParser(XtextTokenStream stream) {
		return new InternalDSLSATParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public DSLSATGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DSLSATGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
