/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.DSLSAT.ui.internal.DSLSATActivator;

public class DSLSATUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DSLSATActivator.getInstance().getInjector("org.xtext.example.mydsl.DSLSAT");
	}

}
