/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.dSLSAT.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.dSLSAT.Annotation;
import org.xtext.example.mydsl.dSLSAT.DSLSATPackage;
import org.xtext.example.mydsl.dSLSAT.Form;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Form</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.dSLSAT.impl.FormImpl#getAnnot <em>Annot</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.dSLSAT.impl.FormImpl#getXheck <em>Xheck</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.dSLSAT.impl.FormImpl#getForm <em>Form</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.dSLSAT.impl.FormImpl#getPath <em>Path</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FormImpl extends MinimalEObjectImpl.Container implements Form
{
  /**
   * The cached value of the '{@link #getAnnot() <em>Annot</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnot()
   * @generated
   * @ordered
   */
  protected Annotation annot;

  /**
   * The default value of the '{@link #getXheck() <em>Xheck</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXheck()
   * @generated
   * @ordered
   */
  protected static final String XHECK_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getXheck() <em>Xheck</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getXheck()
   * @generated
   * @ordered
   */
  protected String xheck = XHECK_EDEFAULT;

  /**
   * The cached value of the '{@link #getForm() <em>Form</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getForm()
   * @generated
   * @ordered
   */
  protected EObject form;

  /**
   * The default value of the '{@link #getPath() <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPath()
   * @generated
   * @ordered
   */
  protected static final String PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPath() <em>Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPath()
   * @generated
   * @ordered
   */
  protected String path = PATH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FormImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DSLSATPackage.Literals.FORM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Annotation getAnnot()
  {
    return annot;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAnnot(Annotation newAnnot, NotificationChain msgs)
  {
    Annotation oldAnnot = annot;
    annot = newAnnot;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DSLSATPackage.FORM__ANNOT, oldAnnot, newAnnot);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAnnot(Annotation newAnnot)
  {
    if (newAnnot != annot)
    {
      NotificationChain msgs = null;
      if (annot != null)
        msgs = ((InternalEObject)annot).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DSLSATPackage.FORM__ANNOT, null, msgs);
      if (newAnnot != null)
        msgs = ((InternalEObject)newAnnot).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DSLSATPackage.FORM__ANNOT, null, msgs);
      msgs = basicSetAnnot(newAnnot, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DSLSATPackage.FORM__ANNOT, newAnnot, newAnnot));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getXheck()
  {
    return xheck;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setXheck(String newXheck)
  {
    String oldXheck = xheck;
    xheck = newXheck;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DSLSATPackage.FORM__XHECK, oldXheck, xheck));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EObject getForm()
  {
    return form;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetForm(EObject newForm, NotificationChain msgs)
  {
    EObject oldForm = form;
    form = newForm;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DSLSATPackage.FORM__FORM, oldForm, newForm);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setForm(EObject newForm)
  {
    if (newForm != form)
    {
      NotificationChain msgs = null;
      if (form != null)
        msgs = ((InternalEObject)form).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DSLSATPackage.FORM__FORM, null, msgs);
      if (newForm != null)
        msgs = ((InternalEObject)newForm).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DSLSATPackage.FORM__FORM, null, msgs);
      msgs = basicSetForm(newForm, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DSLSATPackage.FORM__FORM, newForm, newForm));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPath()
  {
    return path;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPath(String newPath)
  {
    String oldPath = path;
    path = newPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DSLSATPackage.FORM__PATH, oldPath, path));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DSLSATPackage.FORM__ANNOT:
        return basicSetAnnot(null, msgs);
      case DSLSATPackage.FORM__FORM:
        return basicSetForm(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DSLSATPackage.FORM__ANNOT:
        return getAnnot();
      case DSLSATPackage.FORM__XHECK:
        return getXheck();
      case DSLSATPackage.FORM__FORM:
        return getForm();
      case DSLSATPackage.FORM__PATH:
        return getPath();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DSLSATPackage.FORM__ANNOT:
        setAnnot((Annotation)newValue);
        return;
      case DSLSATPackage.FORM__XHECK:
        setXheck((String)newValue);
        return;
      case DSLSATPackage.FORM__FORM:
        setForm((EObject)newValue);
        return;
      case DSLSATPackage.FORM__PATH:
        setPath((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DSLSATPackage.FORM__ANNOT:
        setAnnot((Annotation)null);
        return;
      case DSLSATPackage.FORM__XHECK:
        setXheck(XHECK_EDEFAULT);
        return;
      case DSLSATPackage.FORM__FORM:
        setForm((EObject)null);
        return;
      case DSLSATPackage.FORM__PATH:
        setPath(PATH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DSLSATPackage.FORM__ANNOT:
        return annot != null;
      case DSLSATPackage.FORM__XHECK:
        return XHECK_EDEFAULT == null ? xheck != null : !XHECK_EDEFAULT.equals(xheck);
      case DSLSATPackage.FORM__FORM:
        return form != null;
      case DSLSATPackage.FORM__PATH:
        return PATH_EDEFAULT == null ? path != null : !PATH_EDEFAULT.equals(path);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (xheck: ");
    result.append(xheck);
    result.append(", path: ");
    result.append(path);
    result.append(')');
    return result.toString();
  }

} //FormImpl
