/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.dSLSAT;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Not Form</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.dSLSAT.NotForm#getForm <em>Form</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.dSLSAT.DSLSATPackage#getNotForm()
 * @model
 * @generated
 */
public interface NotForm extends Form
{
  /**
   * Returns the value of the '<em><b>Form</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Form</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Form</em>' containment reference.
   * @see #setForm(Form)
   * @see org.xtext.example.mydsl.dSLSAT.DSLSATPackage#getNotForm_Form()
   * @model containment="true"
   * @generated
   */
  Form getForm();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.dSLSAT.NotForm#getForm <em>Form</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Form</em>' containment reference.
   * @see #getForm()
   * @generated
   */
  void setForm(Form value);

} // NotForm
